[package]
name = "binary_tree"
license = "MIT"
description = "A basic implemenation of a binary search tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dev-dependencies]
proptest = "1.4.0"